exports.categories = [
    'SaaS',
    'Graphics',
    'Databases',
    'Automation',
    'Development',
    'Productivity',
    'DevOps',
    'Video',
]

exports.logos = [
    { filename: 'gatsby', label: 'Gatsby JS', categories: [] },
    { filename: 'material-ui', label: 'Material UI', categories: [] },
    { filename: 'mocha', label: 'Mocha', categories: [] },
    { filename: 'jest', label: 'Jest', categories: [] },
    { filename: 'bootstrap', label: 'Bootstrap', categories: [] },
    { filename: 'ant-design', label: 'Ant Design UI', categories: [] },
    { filename: 'azure', label: 'Azure Cloud', categories: [] },
    { filename: 'css', label: 'CSS', categories: [] },
    { filename: 'deepdetect', label: 'DeepDetect', categories: [] },
    { filename: 'docker(1)', label: 'Docker', categories: [] },
    { filename: 'javascript', label: 'Javascript', categories: [] },
    { filename: 'elementor', label: 'Elementor', categories: [] },
    { filename: 'excel', label: 'Microsoft Excel', categories: [] },
    { filename: 'gitlab', label: 'GitLab', categories: [] },
    { filename: 'graphql', label: 'GraphQL', categories: [] },
    { filename: 'html', label: 'HTML', categories: [] },
    { filename: 'jquery', label: 'jQuery', categories: [] },
    { filename: 'hubspot', label: 'HubSpot', categories: [] },
    { filename: 'mongo', label: 'Mongo DB', categories: [] },
    { filename: 'office', label: 'Microsoft Office', categories: [] },
    { filename: 'postman', label: 'Postman', categories: [] },
    { filename: 'python', label: 'Python', categories: [] },
    { filename: 'redux', label: 'Redux', categories: [] },
    { filename: 'shopify', label: 'Shopify', categories: [] },
    { filename: 'selenium', label: 'Selenium', categories: [] },
    { filename: 'tailwind-css', label: 'Tailwind CSS', categories: [] },
    { filename: 'ubuntu', label: 'Ubuntu', categories: [] },
    { filename: 'visual-studio', label: 'Visual Studio', categories: [] },
    { filename: 'windows', label: 'Windows', categories: [] },
    { filename: 'wordpress-blue', label: 'WordPress', categories: [] },
    { filename: 'woocommerce', label: 'WooCommerce', categories: [] },
    { filename: 'adobe-photoshop-cs6', label: 'Photoshop', categories: [] },
    { filename: 'mailchimp', label: 'MailChimp', categories: [] },
    { filename: 'slack-1', label: 'Slack', categories: [] },
]